#!/bin/bash

# Copyright (c) 2016, Rice University
# All rights reserved.
#
# Author(s): Neil T. Dantam <ntd@rice.edu>
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#   * Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#  COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
#  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
#  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
#  OF THE POSSIBILITY OF SUCH DAMAGE.



## TODO: escape special characters in file names

# TMSMT_GUI=nil
# TMSMT_PAUSE=nil
# TMSMT_VERBOSE=nil

while test "$1" != x-- -a "x$#" != x0; do
    case "$1" in
        -h|-\?|--help)
            cat <<EOF
Usage: tmsmt [OPTIONS] FILES...
Compute a task-motion plan

Options:
  -s SCENE_FILE               Start scene file
  -G,--gui                    Enable graphical interface
  -P,--pause                  Pause after planning to display plan
  -v                          Be verbose

Examples:
  tmsmt -s 'package://baxter_description/urdf/baxter.urdf' -s file.robray
EOF
            exit 0
            ;;
        -s)
            shift;
            export TMSMT_SCENE_FILES="${TMSMT_SCENE_FILES} \"$1\""
            ;;
        -G|--gui)
            export TMSMT_GUI=1
            ;;
        -P|--pause)
            export TMSMT_PAUSE=1
            ;;
        -v)
            export TMSMT_VERBOSE=1
            ;;
        *)
            >&2 echo "tmsmt: unrecognized option '$1'"
            >&2 echo "Try 'tmsmt --help' for more information."
            exit 1
            ;;
    esac
    shift
done

# tmsmt.core --quit --eval '(ql:quickload :tmsmt)' --eval '(tmsmt::tmp-command)'
tmsmt.core --non-interactive \
           --eval '(tmsmt::tmp-command)'
