(define (domain itmp)
  (:requirements :typing)
  (:types location
          cup pitcher bowl - object
          dripper - cup
          ingredient)
  (:predicates (at ?obj - object ?loc - location )
               (occupied ?loc - location)
               (contains ?obj - object ?ingredient)
               (on ?x - object ?y - object)
               (contains-beverage ?cup - cup ?x - ingredient)
               (covered ?x - object)
               (used ?x - object)
               (full ?x - object)
               (empty ?x - object)
               (holding ?x - object)
               (hand-empty)
               )
  (:action transfer
           :parameters (?x - location ?y - location ?obj - object)
           :precondition (and (at ?obj ?x)
                              (not (occupied ?y))
                              (hand-empty))
           :effect (and (not (at ?obj ?x))
                        (not (occupied ?x))
                        (at ?obj ?y)
                        (occupied ?y)))
  (:action pick
           :parameters (?x - location ?obj - object)
           :precondition (and (at ?obj ?x)
                              (hand-empty))
           :effect (and (not (at ?obj ?x))
                        (not (occupied ?x))
                        (not (hand-empty))
                        (holding ?obj)))

  (:action place
           :parameters (?y - location ?obj - object)
           :precondition (and (not (occupied ?y))
                              (holding ?obj))
           :effect (and (not (holding ?obj))
                        (hand-empty)
                        (at ?obj ?y)
                        (occupied ?y)))
  (:action stack
           :parameters (?a - object ?b - object)
           :precondition (and (not (covered ?b))
                              (holding ?a))
           :effect (and (covered ?b)
                        (on ?a ?b)
                        (not (holding ?a))
                        (hand-empty)))
  (:action unstack
           :parameters (?a - object ?b - object)
           :precondition (and (not (covered ?a))
                              (on ?a ?b)
                              (hand-empty))
           :effect (and (not (covered ?b))
                        (not (on ?a ?b))
                        (not (hand-empty))
                        (holding ?a)))
  (:action spoon
           :parameters (?x - ingredient ?bowl - bowl ?cup - cup)
           :precondition (and (contains ?bowl ?x)
                              (not (full ?cup))
                              (empty ?cup)
                              (hand-empty)
                              )
           :effect (and (contains ?cup ?x)
                        (not (empty ?cup))))
  (:action pour-over
           :parameters (?dripper - dripper ?cup - cup ?beans - ingredient)
           :precondition (and (on ?dripper ?cup)
                              (contains ?dripper ?beans)
                              (not (used ?dripper))
                              )
           :effect (and (contains-beverage ?cup ?beans)
                        (used ?dripper)
                        ))
  (:action dump
           :parameters (?cup - cup ?x - ingredient)
           :precondition (and (used ?cup)
                              (contains ?cup ?x)
                              (holding ?cup))
           :effect (and (not (used ?cup))
                        (not (contains ?cup ?x))
                        (empty ?cup))))
